version: '3'


services:

  server:
    build: .
    command: ./blog
    restart: always
    container_name: blog_server
    ports:
      - 8081:8081
    networks:
      - microservice_network
      - server_db
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: blog_db
    env_file:
      - ./pkg/config/envs/prod.db.env
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - server_db

volumes:
  data:


networks:
  microservice_network:
    external: true
  server_db:
