version: '3'

services:
  frontend:
    build: .
    restart: always
    command: npm run start
    container_name: frontend_client
    networks:
      - gateway_network
    ports:
      - "5173:5173"
    volumes:
      - frontend_static:/app/frontend

networks:
  gateway_network:
    external: true

volumes:
  frontend_static:
