version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: always
    container_name: zoomerok_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka_network

  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    container_name: zoomerok_kafka
    ports:
      - "9092:9092" # Внутренний порт для связи между контейнерами
      - "9094:9094" # Внешний порт для подключения с хост-машины
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    hostname: kafka
    networks:
      - kafka_network
      - microservice_network


networks:
  kafka_network:
  microservice_network:
    external: true