version: '3'


services:
  nginx:
    build: .
    restart: always
    container_name: gateway_nginx
    ports:
      - 1337:80
    networks:
      - gateway_network
    volumes:
      - frontend_static:/usr/share/nginx/html


networks:
  gateway_network:
    external: true

volumes:
  frontend_static:
