version: '3'


services:
  nginx:
    build: .
    restart: always
    container_name: gateway_nginx
    ports:
      - 1337:80
    networks:
      - microservice_network
    command: ["sh", "-c", "sleep 5 && nginx -g 'daemon off;'"]


networks:
  microservice_network:
    external: true
